export { default as Home } from "./home";
export { default as OnBoarding } from "./on-boarding";
export { default as BuyGiftCard } from "./buy-giftcard";
export { default as SellGiftcard } from "./sell-giftcard";
// export { default as Wallet } from "./wallet";
export { default as Transactions } from "./transactions";
export { default as Coin } from "./coin";
export { default as SignIn } from "./sign-in";
export { default as SignUp } from "./sign-up";
// export { default as Profile } from "./profile";
export { default as Verification } from "./Verification";
export { default as Landing } from "./landing";
export { default as About } from "./about";
export { default as AboutRates } from "./about-rates";
export { default as BTC } from "./btc";
export { default as Bills } from "./bills";
export { default as Airtime } from "./airtime";
export { default as Settings } from "./settings";
export { default as CryptoView } from "./crypto";
export { default as VerifyEmail } from "./verify_email";
export {default as NotFoundApp} from "./not-found-app";
export {default as NotFoundIndex} from "./not-found-index";