// Auth -done - confirm if it has either toaster or modal notification indicator in the reducers
export const CHECK_EMAIL_AVAILABILITY_PENDING = "CHECK_EMAIL_AVAILABILITY_PENDING";
export const CHECK_EMAIL_AVAILABILITY_SUCCESS = "CHECK_EMAIL_AVAILABILITY_SUCCESS";
export const CHECK_EMAIL_AVAILABILITY_FAILED = "CHECK_EMAIL_AVAILABILITY_FAILED";

export const REGISTER_PENDING = "REGISTER_PENDING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_PENDING = "LOGOUT_PENDING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const VERIFY_EMAIL_OTP_PENDING = "VERIFY_EMAIL_OTP_PENDING";
export const VERIFY_EMAIL_OTP_SUCCESS = "VERIFY_EMAIL_OTP_SUCCESS";
export const VERIFY_EMAIL_OTP_FAILED = "VERIFY_EMAIL_OTP_FAILED";

export const RESEND_EMAIL_OTP_CODE_PENDING = "RESEND_EMAIL_OTP_CODE_PENDING";
export const RESEND_EMAIL_OTP_CODE_SUCCESS = "RESEND_EMAIL_OTP_CODE_SUCCESS";
export const RESEND_EMAIL_OTP_CODE_FAILED = "RESEND_EMAIL_OTP_CODE_FAILED";

export const CHANGE_USER_PASSWORD_PENDING = "CHANGE_USER_PASSWORD_PENDING";
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS";
export const CHANGE_USER_PASSWORD_FAILED = "CHANGE_USER_PASSWORD_FAILED";

export const RESET_USER_PASSWORD_PENDING = "RESET_USER_PASSWORD_PENDING";
export const RESET_USER_PASSWORD_SUCCESS = "RESET_USER_PASSWORD_SUCCESS";
export const RESET_USER_PASSWORD_FAILED = "RESET_USER_PASSWORD_FAILED";

export const COMPLETE_RESET_USER_PASSWORD_PENDING = "COMPLETE_RESET_USER_PASSWORD_PENDING";
export const COMPLETE_RESET_USER_PASSWORD_SUCCESS = "COMPLETE_RESET_USER_PASSWORD_SUCCESS";
export const COMPLETE_RESET_USER_PASSWORD_FAILED = "COMPLETE_RESET_USER_PASSWORD_FAILED";

//user

export const GET_USER_DETAILS_BY_ID_PENDING = "GET_USER_DETAILS_BY_ID_PENDING";
export const GET_USER_DETAILS_BY_ID_SUCCESS = "GET_USER_DETAILS_BY_ID_SUCCESS";
export const GET_USER_DETAILS_BY_ID_FAILED = "GET_USER_DETAILS_BY_ID_FAILED";

export const UPDATE_USER_DETAILS_PENDING = "UPDATE_USER_DETAILS_PENDING";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAILED = "UPDATE_USER_DETAILS_FAILED";

export const SET_TRANSACTION_PIN_PENDING = "SET_TRANSACTION_PIN_PENDING";
export const SET_TRANSACTION_PIN_SUCCESS = "SET_TRANSACTION_PIN_SUCCESS";
export const SET_TRANSACTION_PIN_FAILED = "SET_TRANSACTION_PIN_FAILED";

export const RESET_TRANSACTION_PIN_PENDING = "RESET_TRANSACTION_PIN_PENDING";
export const RESET_TRANSACTION_PIN_SUCCESS = "RESET_TRANSACTION_PIN_SUCCESS";
export const RESET_TRANSACTION_PIN_FAILED = "RESET_TRANSACTION_PIN_FAILED";

export const COMPLETE_RESET_TRANSACTION_PIN_PENDING = "COMPLETE_RESET_TRANSACTION_PIN_PENDING";
export const COMPLETE_RESET_TRANSACTION_PIN_SUCCESS = "COMPLETE_RESET_TRANSACTION_PIN_SUCCESS";
export const COMPLETE_RESET_TRANSACTION_PIN_FAILED = "COMPLETE_RESET_TRANSACTION_PIN_FAILED";

export const ADD_BANK_ACCOUNT_PENDING = "ADD_BANK_ACCOUNT_PENDING";
export const ADD_BANK_ACCOUNT_SUCCESS = "ADD_BANK_ACCOUNT_SUCCESS";
export const ADD_BANK_ACCOUNT_FAILED = "ADD_BANK_ACCOUNT_FAILED";

export const GET_BANK_ACCOUNT_PENDING = "GET_BANK_ACCOUNT_PENDING";
export const GET_BANK_ACCOUNT_SUCCESS = "GET_BANK_ACCOUNT_SUCCESS";
export const GET_BANK_ACCOUNT_FAILED = "GET_BANK_ACCOUNT_FAILED";

export const DEL_BANK_ACCOUNT_PENDING = "DEL_BANK_ACCOUNT_PENDING";
export const DEL_BANK_ACCOUNT_SUCCESS = "DEL_BANK_ACCOUNT_SUCCESS";
export const DEL_BANK_ACCOUNT_FAILED = "DEL_BANK_ACCOUNT_FAILED";

// BTC

export const GET_WALLET_DETAILS_PENDING = "GET_WALLET_DETAILS_PENDING";
export const GET_WALLET_DETAILS_SUCCESS = "GET_WALLET_DETAILS_SUCCESS";
export const GET_WALLET_DETAILS_FAILED = "GET_WALLET_DETAILS_FAILED";

export const GET_CURRENT_MARKET_TICKERS_PENDING = "GET_CURRENT_MARKET_TICKERS_PENDING";
export const GET_CURRENT_MARKET_TICKERS_SUCCESS = "GET_CURRENT_MARKET_TICKERS_SUCCESS";
export const GET_CURRENT_MARKET_TICKERS_FAILED = "GET_CURRENT_MARKET_TICKERS_FAILED";

export const INITIAL_BUY_BTC_PENDING = "INITIAL_BUY_BTC_PENDING";
export const INITIAL_BUY_BTC_SUCCESS = "INITIAL_BUY_BTC_SUCCESS";
export const INITIAL_BUY_BTC_FAILED = "INITIAL_BUY_BTC_FAILED";

export const INITIAL_SELL_BTC_PENDING = "INITIAL_SELL_BTC_PENDING";
export const INITIAL_SELL_BTC_SUCCESS = "INITIAL_SELL_BTC_SUCCESS";
export const INITIAL_SELL_BTC_FAILED = "INITIAL_SELL_BTC_FAILED";

export const INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_PENDING = "INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_PENDING";
export const INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_SUCCESS = "INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_SUCCESS";
export const INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_FAILED = "INITIAL_SEND_BTC_TO_EXTERNAL_WALLET_FAILED";

export const RECEIVE_BTC_PENDING = "RECEIVE_BTC_PENDING";
export const RECEIVE_BTC_SUCCESS = "RECEIVE_BTC_SUCCESS";
export const RECEIVE_BTC_FAILED = "RECEIVE_BTC_FAILED";

export const GET_TRANSACTION_HISTORY_PENDING = "GET_TRANSACTION_HISTORY_PENDING";
export const GET_TRANSACTION_HISTORY_SUCCESS = "GET_TRANSACTION_HISTORY_SUCCESS";
export const GET_TRANSACTION_HISTORY_FAILED = "GET_TRANSACTION_HISTORY_FAILED";

export const GET_LAST_TRANSACTION_HISTORY_PENDING = "GET_LAST_TRANSACTION_HISTORY_PENDING";
export const GET_LAST_TRANSACTION_HISTORY_SUCCESS = "GET_LAST_TRANSACTION_HISTORY_SUCCESS";
export const GET_LAST_TRANSACTION_HISTORY_FAILED = "GET_TRANSACTION_HISTORY_FAILED";

export const CANCEL_OPEN_TRANSACTIONS_PENDING = "CANCEL_OPEN_TRANSACTIONS_PENDING";
export const CANCEL_OPEN_TRANSACTIONS_SUCCESS = "CANCEL_OPEN_TRANSACTIONS_SUCCESS";
export const CANCEL_OPEN_TRANSACTIONS_FAILED = "CANCEL_OPEN_TRANSACTIONS_FAILED";

// payment

export const INITIAL_PAYMENT_PENDING = "INITIAL_PAYMENT_PENDING";
export const INITIAL_PAYMENT_SUCCESS = "INITIAL_PAYMENT_SUCCESS";
export const INITIAL_PAYMENT_FAILED = "INITIAL_PAYMENT_FAILED";

export const CANCEL_PAYMENT_PENDING = "CANCEL_PAYMENT_PENDING";
export const CANCEL_PAYMENT_SUCCESS = "CANCEL_PAYMENT_SUCCESS";
export const CANCEL_PAYMENT_FAILED = "CANCEL_PAYMENT_FAILED";

export const GET_PAYMENT_DETAILS_PENDING = "GET_PAYMENT_DETAILS_PENDING";
export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
export const GET_PAYMENT_DETAILS_FAILED = "GET_PAYMENT_DETAILS_FAILED";

export const GET_LAST_PAYMENT_BY_USER_PENDING = "GET_LAST_PAYMENT_BY_USER_PENDING";
export const GET_LAST_PAYMENT_BY_USER_SUCCESS = "GET_LAST_PAYMENT_BY_USER_SUCCESS";
export const GET_LAST_PAYMENT_BY_USER_FAILED = "GET_LAST_PAYMENT_BY_USER_FAILED";

export const GET_ALL_PAYMENT_BY_USER_PENDING = "GET_ALL_PAYMENT_BY_USER_PENDING";
export const GET_ALL_PAYMENT_BY_USER_SUCCESS = "GET_ALL_PAYMENT_BY_USER_SUCCESS";
export const GET_ALL_PAYMENT_BY_USER_FAILED = "GET_ALL_PAYMENT_BY_USER_FAILED";

// GIFTCARD

// export const GET_PAYMENT_DETAILS_PENDING = "GET_PAYMENT_DETAILS_PENDING";
// export const GET_PAYMENT_DETAILS_SUCCESS = "GET_PAYMENT_DETAILS_SUCCESS";
// export const GET_PAYMENT_DETAILS_FAILED = "GET_PAYMENT_DETAILS_FAILED";

// export const GET_ALL_PAYMENT_BY_USER_PENDING = "GET_ALL_PAYMENT_BY_USER_PENDING";
// export const GET_ALL_PAYMENT_BY_USER_SUCCESS = "GET_ALL_PAYMENT_BY_USER_SUCCESS";
// export const GET_ALL_PAYMENT_BY_USER_FAILED = "GET_ALL_PAYMENT_BY_USER_FAILED";

export const GET_CARD_CODES_PENDING = "GET_CARD_CODES_PENDING";
export const GET_CARD_CODES_SUCCESS = "GET_CARD_CODES_SUCCESS";
export const GET_CARD_CODES_FAILED = "GET_CARD_CODES_FAILED";

export const INITIATE_SELL_GIFTCARD_PENDING = "INITIATE_SELL_GIFTCARD_PENDING";
export const INITIATE_SELL_GIFTCARD_SUCCESS = "INITIATE_SELL_GIFTCARD_SUCCESS";
export const INITIATE_SELL_GIFTCARD_FAILED = "INITIATE_SELL_GIFTCARD_FAILED";

export const CANCEL_SELL_GIFTCARD_TRANSACTION_PENDING = "CANCEL_SELL_GIFTCARD_TRANSCTION_PENDING";
export const CANCEL_SELL_GIFTCARD_TRANSACTION_SUCCESS = "CANCEL_SELL_GIFTCARD_TRANSCTION_SUCCESS";
export const CANCEL_SELL_GIFTCARD_TRANSACTION_FAILED = "CANCEL_SELL_GIFTCARD_TRANSCTION_FAILED";

export const GET_TRANSACTION_DETAILS_GIFTCARD_PENDING = "GET_TRANSACTION_DETAILS_GIFTCARD_PENDING";
export const GET_TRANSACTION_DETAILS_GIFTCARD_SUCCESS = "GET_TRANSACTION_DETAILS_GIFTCARD_SUCCESS";
export const GET_TRANSACTION_DETAILS_GIFTCARD_FAILED = "GET_TRANSACTION_DETAILS_GIFTCARD_FAILED";

export const GET_TRANSACTIONS_HISTORY_GIFTCARD_PENDING = "GET_TRANSACTIONS_HISTORY_GIFTCARD_PENDING";
export const GET_TRANSACTIONS_HISTORY_GIFTCARD_SUCCESS = "GET_TRANSACTIONS_HISTORY_GIFTCARD_SUCCESS";
export const GET_TRANSACTIONS_HISTORY_GIFTCARD_FAILED = "GET_TRANSACTIONS_HISTORY_GIFTCARD_FAILED";

export const GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_PENDING = "GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_PENDING";
export const GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_SUCCESS = "GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_SUCCESS";
export const GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_FAILED = "GET_LAST_TRANSACTIONS_HISTORY_GIFTCARD_FAILED";

// MISC

export const GET_BANKS_BY_COUNTRY_PENDING = "GET_BANKS_BY_COUNTRY_PENDING";
export const GET_BANKS_BY_COUNTRY_SUCCESS = "GET_BANKS_BY_COUNTRY_SUCCESS";
export const GET_BANKS_BY_COUNTRY_FAILED = "GET_BANKS_BY_COUNTRY_FAILED";

export const VERIFY_BANK_ACCOUNT_DETAILS_PENDING = "VERIFY_BANK_ACCOUNT_DETAILS_PENDING";
export const VERIFY_BANK_ACCOUNT_DETAILS_SUCCESS = "VERIFY_BANK_ACCOUNT_DETAILS_SUCCESS";
export const VERIFY_BANK_ACCOUNT_DETAILS_FAILED = "VERIFY_BANK_ACCOUNT_DETAILS_FAILED";

export const AUTH_TOKEN = 'auth_token'
export const AUTH_TOKEN_ID = 'auth_token_id'
export const KEY = 'update_key';

// withdrawal

export const INITIAL_WITHDRAWAL_PENDING = "INITIAL_WITHDRAWAL_PENDING";
export const INITIAL_WITHDRAWAL_SUCCESS = "INITIAL_WITHDRAWAL_SUCCESS";
export const INITIAL_WITHDRAWAL_FAILED = "INITIAL_WITHDRAWAL_FAILED";

export const CANCEL_WITHDRAWAL_PENDING = "CANCEL_WITHDRAWAL_PENDING";
export const CANCEL_WITHDRAWAL_SUCCESS = "CANCEL_WITHDRAWAL_SUCCESS";
export const CANCEL_WITHDRAWAL_FAILED = "CANCEL_WITHDRAWAL_FAILED";

export const GET_WITHDRAWAL_DETAILS_PENDING = "GET_WITHDRAWAL_DETAILS_PENDING";
export const GET_WITHDRAWAL_DETAILS_SUCCESS = "GET_WITHDRAWAL_DETAILS_SUCCESS";
export const GET_WITHDRAWAL_DETAILS_FAILED = "GET_WITHDRAWAL_DETAILS_FAILED";

export const GET_LAST_WITHDRAWAL_BY_USER_PENDING = "GET_LAST_WITHDRAWAL_BY_USER_PENDING";
export const GET_LAST_WITHDRAWAL_BY_USER_SUCCESS = "GET_LAST_WITHDRAWAL_BY_USER_SUCCESS";
export const GET_LAST_WITHDRAWAL_BY_USER_FAILED = "GET_LAST_WITHDRAWAL_BY_USER_FAILED";

export const GET_ALL_WITHDRAWAL_BY_USER_PENDING = "GET_ALL_WITHDRAWAL_BY_USER_PENDING";
export const GET_ALL_WITHDRAWAL_BY_USER_SUCCESS = "GET_ALL_WITHDRAWAL_BY_USER_SUCCESS";
export const GET_ALL_WITHDRAWAL_BY_USER_FAILED = "GET_ALL_WITHDRAWAL_BY_USER_FAILED";

// const LoginUser = data => async dispatch => {
//   dispatch({
//     type: actionTypes.LOGIN_PENDING,
//   })
// }

// export const loginUser = data => dispatch => {
//   // done
//   dispatch(LoginUser(data));
// };